// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: see_new_hires.proto

package newHire.find.newhires;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
