# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_email.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='create_email.proto',
  package='newHire',
  syntax='proto3',
  serialized_options=b'\n\030grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63reate_email.proto\x12\x07newHire\"\x1d\n\rEmailToCreate\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\x0c\x45mailCreated\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\rEmailToDelete\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\x0c\x45mailDeleted\x12\r\n\x05value\x18\x01 \x01(\t\"\x16\n\x06\x45mails\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1a\n\tAllEmails\x12\r\n\x05value\x18\x01 \x01(\t2\xbf\x01\n\x07newHire\x12>\n\x0b\x63reateEmail\x12\x16.newHire.EmailToCreate\x1a\x15.newHire.EmailCreated\"\x00\x12>\n\x0b\x64\x65leteEmail\x12\x16.newHire.EmailToDelete\x1a\x15.newHire.EmailDeleted\"\x00\x12\x34\n\tseeEmails\x12\x0f.newHire.Emails\x1a\x12.newHire.AllEmails\"\x00\x30\x01\x42\x33\n\x18grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_EMAILTOCREATE = _descriptor.Descriptor(
  name='EmailToCreate',
  full_name='newHire.EmailToCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='newHire.EmailToCreate.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=60,
)


_EMAILCREATED = _descriptor.Descriptor(
  name='EmailCreated',
  full_name='newHire.EmailCreated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='newHire.EmailCreated.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)


_EMAILTODELETE = _descriptor.Descriptor(
  name='EmailToDelete',
  full_name='newHire.EmailToDelete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='newHire.EmailToDelete.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=122,
)


_EMAILDELETED = _descriptor.Descriptor(
  name='EmailDeleted',
  full_name='newHire.EmailDeleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='newHire.EmailDeleted.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=153,
)


_EMAILS = _descriptor.Descriptor(
  name='Emails',
  full_name='newHire.Emails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='newHire.Emails.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=177,
)


_ALLEMAILS = _descriptor.Descriptor(
  name='AllEmails',
  full_name='newHire.AllEmails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='newHire.AllEmails.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['EmailToCreate'] = _EMAILTOCREATE
DESCRIPTOR.message_types_by_name['EmailCreated'] = _EMAILCREATED
DESCRIPTOR.message_types_by_name['EmailToDelete'] = _EMAILTODELETE
DESCRIPTOR.message_types_by_name['EmailDeleted'] = _EMAILDELETED
DESCRIPTOR.message_types_by_name['Emails'] = _EMAILS
DESCRIPTOR.message_types_by_name['AllEmails'] = _ALLEMAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailToCreate = _reflection.GeneratedProtocolMessageType('EmailToCreate', (_message.Message,), {
  'DESCRIPTOR' : _EMAILTOCREATE,
  '__module__' : 'create_email_pb2'
  # @@protoc_insertion_point(class_scope:newHire.EmailToCreate)
  })
_sym_db.RegisterMessage(EmailToCreate)

EmailCreated = _reflection.GeneratedProtocolMessageType('EmailCreated', (_message.Message,), {
  'DESCRIPTOR' : _EMAILCREATED,
  '__module__' : 'create_email_pb2'
  # @@protoc_insertion_point(class_scope:newHire.EmailCreated)
  })
_sym_db.RegisterMessage(EmailCreated)

EmailToDelete = _reflection.GeneratedProtocolMessageType('EmailToDelete', (_message.Message,), {
  'DESCRIPTOR' : _EMAILTODELETE,
  '__module__' : 'create_email_pb2'
  # @@protoc_insertion_point(class_scope:newHire.EmailToDelete)
  })
_sym_db.RegisterMessage(EmailToDelete)

EmailDeleted = _reflection.GeneratedProtocolMessageType('EmailDeleted', (_message.Message,), {
  'DESCRIPTOR' : _EMAILDELETED,
  '__module__' : 'create_email_pb2'
  # @@protoc_insertion_point(class_scope:newHire.EmailDeleted)
  })
_sym_db.RegisterMessage(EmailDeleted)

Emails = _reflection.GeneratedProtocolMessageType('Emails', (_message.Message,), {
  'DESCRIPTOR' : _EMAILS,
  '__module__' : 'create_email_pb2'
  # @@protoc_insertion_point(class_scope:newHire.Emails)
  })
_sym_db.RegisterMessage(Emails)

AllEmails = _reflection.GeneratedProtocolMessageType('AllEmails', (_message.Message,), {
  'DESCRIPTOR' : _ALLEMAILS,
  '__module__' : 'create_email_pb2'
  # @@protoc_insertion_point(class_scope:newHire.AllEmails)
  })
_sym_db.RegisterMessage(AllEmails)


DESCRIPTOR._options = None

_NEWHIRE = _descriptor.ServiceDescriptor(
  name='newHire',
  full_name='newHire.newHire',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=399,
  methods=[
  _descriptor.MethodDescriptor(
    name='createEmail',
    full_name='newHire.newHire.createEmail',
    index=0,
    containing_service=None,
    input_type=_EMAILTOCREATE,
    output_type=_EMAILCREATED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteEmail',
    full_name='newHire.newHire.deleteEmail',
    index=1,
    containing_service=None,
    input_type=_EMAILTODELETE,
    output_type=_EMAILDELETED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='seeEmails',
    full_name='newHire.newHire.seeEmails',
    index=2,
    containing_service=None,
    input_type=_EMAILS,
    output_type=_ALLEMAILS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEWHIRE)

DESCRIPTOR.services_by_name['newHire'] = _NEWHIRE

# @@protoc_insertion_point(module_scope)
