// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_security_card.proto

package newHire.create.security.card;

public interface CardDeletedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire.CardDeleted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
