// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_permissions.proto

package newHire.create.permissions;

public interface CreatedPermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire.CreatedPermission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
