// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_permissions.proto

package newHire.create.permissions;

public final class newHire2ServiceImpl {
  private newHire2ServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_permissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_permissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_permissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_permissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_RequestPermissions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_RequestPermissions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_AllPermissions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_AllPermissions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_NewPermission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_NewPermission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_CreatedPermission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_CreatedPermission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030create_permissions.proto\022\007newHire\"!\n\021p" +
      "ermissionRequest\022\014\n\004text\030\001 \001(\t\"#\n\022permis" +
      "sionResponse\022\r\n\005value\030\001 \001(\t\"\"\n\022RequestPe" +
      "rmissions\022\014\n\004text\030\001 \001(\t\"\037\n\016AllPermission" +
      "s\022\r\n\005value\030\001 \001(\t\"\035\n\rNewPermission\022\014\n\004tex" +
      "t\030\001 \001(\t\"\"\n\021CreatedPermission\022\r\n\005value\030\001 " +
      "\001(\t2\345\001\n\007newHire\022J\n\013Permissions\022\032.newHire" +
      ".permissionRequest\032\033.newHire.permissionR" +
      "esponse(\0010\001\022H\n\016seePermissions\022\033.newHire." +
      "RequestPermissions\032\027.newHire.AllPermissi" +
      "ons0\001\022D\n\016setPermissions\022\026.newHire.NewPer" +
      "mission\032\032.newHire.CreatedPermissionB3\n\032n" +
      "ewHire.create.permissionsB\023newHire2Servi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_newHire_permissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_newHire_permissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_permissionRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_permissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newHire_permissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_permissionResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_newHire_RequestPermissions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_newHire_RequestPermissions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_RequestPermissions_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_AllPermissions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_newHire_AllPermissions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_AllPermissions_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_newHire_NewPermission_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_newHire_NewPermission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_NewPermission_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_CreatedPermission_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_newHire_CreatedPermission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_CreatedPermission_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
