// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_permissions.proto

package newHire.create.permissions;

public interface NewPermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire.NewPermission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
