// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_email.proto

package newHire.create.email;

public interface AllEmailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire.AllEmails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
