// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_email.proto

package newHire.create.email;

public interface EmailToDeleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire.EmailToDelete)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
