// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_email.proto

package newHire.create.email;

public final class newHire2ServiceImpl {
  private newHire2ServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_MessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022create_email.proto\022\007newHire\"\036\n\016Message" +
      "Request\022\014\n\004text\030\001 \001(\t\"\035\n\014MessageReply\022\r\n" +
      "\005value\030\001 \001(\t2H\n\007newHire\022=\n\013sendMessage\022\027" +
      ".newHire.MessageRequest\032\025.newHire.Messag" +
      "eReplyB-\n\024newHire.create.emailB\023newHire2" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_newHire_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_newHire_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_MessageRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newHire_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_MessageReply_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
