// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_email.proto

package newHire.create.email;

public final class newHire2ServiceImpl {
  private newHire2ServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_MessageReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_EmailToDelete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_EmailToDelete_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_EmailDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_EmailDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_Emails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_Emails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire_AllEmails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire_AllEmails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022create_email.proto\022\007newHire\"\036\n\016Message" +
      "Request\022\014\n\004text\030\001 \001(\t\"\035\n\014MessageReply\022\r\n" +
      "\005value\030\001 \001(\t\"\035\n\rEmailToDelete\022\014\n\004text\030\001 " +
      "\001(\t\"\035\n\014EmailDeleted\022\r\n\005value\030\001 \001(\t\"\026\n\006Em" +
      "ails\022\014\n\004text\030\001 \001(\t\"\032\n\tAllEmails\022\r\n\005value" +
      "\030\001 \001(\t2\272\001\n\007newHire\022=\n\013sendMessage\022\027.newH" +
      "ire.MessageRequest\032\025.newHire.MessageRepl" +
      "y\022<\n\013deleteEmail\022\026.newHire.EmailToDelete" +
      "\032\025.newHire.EmailDeleted\0222\n\tseeEmails\022\017.n" +
      "ewHire.Emails\032\022.newHire.AllEmails0\001B-\n\024n" +
      "ewHire.create.emailB\023newHire2ServiceImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_newHire_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_newHire_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_MessageRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newHire_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_MessageReply_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_newHire_EmailToDelete_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_newHire_EmailToDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_EmailToDelete_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_EmailDeleted_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_newHire_EmailDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_EmailDeleted_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_newHire_Emails_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_newHire_Emails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_Emails_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire_AllEmails_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_newHire_AllEmails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire_AllEmails_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
