// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_security_card.proto

package create.security.card;

public final class newHire2ServiceImpl {
  private newHire2ServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire1_card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire1_card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire1_cardCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire1_cardCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire1_RequestCards_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire1_RequestCards_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire1_CardsReturned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire1_CardsReturned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire1_SpecifyCard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire1_SpecifyCard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newHire1_CardDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newHire1_CardDeleted_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032create_security_card.proto\022\010newHire1\"\024" +
      "\n\004card\022\014\n\004text\030\001 \001(\t\"\034\n\013cardCreated\022\r\n\005v" +
      "alue\030\001 \001(\t\"\034\n\014RequestCards\022\014\n\004text\030\001 \001(\t" +
      "\"\036\n\rCardsReturned\022\r\n\005value\030\001 \001(\t\"\033\n\013Spec" +
      "ifyCard\022\014\n\004text\030\001 \001(\t\"\034\n\013CardDeleted\022\r\n\005" +
      "value\030\001 \001(\t2\274\001\n\010newHire1\0225\n\ncreateCard\022\016" +
      ".newHire1.card\032\025.newHire1.cardCreated(\001\022" +
      "=\n\010seeCards\022\026.newHire1.RequestCards\032\027.ne" +
      "wHire1.CardsReturned0\001\022:\n\ndeleteCard\022\025.n" +
      "ewHire1.SpecifyCard\032\025.newHire1.CardDelet" +
      "edB-\n\024create.security.cardB\023newHire2Serv" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_newHire1_card_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_newHire1_card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire1_card_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire1_cardCreated_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newHire1_cardCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire1_cardCreated_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_newHire1_RequestCards_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_newHire1_RequestCards_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire1_RequestCards_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire1_CardsReturned_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_newHire1_CardsReturned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire1_CardsReturned_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_newHire1_SpecifyCard_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_newHire1_SpecifyCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire1_SpecifyCard_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_newHire1_CardDeleted_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_newHire1_CardDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newHire1_CardDeleted_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
