// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: create_security_card.proto

package create.security.card;

public interface RequestCardsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newHire1.RequestCards)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
